// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SherlockHUD-Demo",
    platforms: [
        .iOS("14.0")
    ],
    products: [
        .iOSApplication(
            name: "SherlockHUD-Demo",
            targets: ["AppModule"],
            bundleIdentifier: "com.inamiy.SherlockHUD-Demo",
            teamIdentifier: "UMBZ5WL247",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        // .package(url: "https://github.com/inamiy/SherlockForms", from: "0.1.0")
        .package(name: "SherlockForms", path: "../../")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .productItem(name: "SherlockHUD", package: "SherlockForms", condition: nil)
            ],
            path: ".",
            swiftSettings: [.unsafeFlags(["-warn-concurrency"], .when(configuration: .debug))]
        )
    ]

)
